pipeline {
    agent any

    stages {
        stage ('Compile Stage') {

            steps {
                withMaven(Maven : 'apache-maven-3.6.3') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage ('Testing Stage') {

            steps {
                withMaven(Maven : 'apache-maven-3.6.3') {
                    sh 'mvn test'
                }
            }
        }


        stage ('Deployment Stage') {
            steps {
                withMaven(Maven : 'apache-maven-3.6.3') {
                    sh 'mvn deploy'
                }
            }
        }
    }
}
